title: Michaela Coetsee - Data Science Portfolio
description: A driven MSc Data Science graduate, experienced in research and commited to continuous learning, ethical AI, and utilising data science for social good.
logo: SriLanka.png
show_downloads: false
github: false
theme: jekyll-theme-minimal

