title: Michaela Coetsee - Data Science Portfolio
description: A driven MSc Data Science graduate experiencd in research, with a passion for continuous learning and utilising data science for social good.
show_downloads: false
github: false
theme: jekyll-theme-hyde
