title: GitHub Data Science Portfolio - Michaela Coetsee
description: A driven MSc Data Science graduate with a passion for continuous learning and utilising data science for social good.
# show_downloads: true 
theme: jekyll-theme-minimal
