title: Data Science Portfolio - Michaela Coetsee
description: A driven MSc Data Science graduate experiencd in research, with a passion for continuous learning and utilising data science for social good.
# show_downloads: true 
theme: jekyll-theme-minimal
